version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      # Performance settings
      MONGO_INITDB_DATABASE: admin
      MONGODB_WIREDTIGER_CACHE_SIZE_GB: "1"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./mongo-init:/docker-entrypoint-initdb.d
    command: ["--auth", "--wiredTigerCacheSizeGB", "1", "--bind_ip_all"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.adminCommand(\"ping\").ok'", "localhost:27017/admin", "-u", "root", "-p", "root", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local